### ISSUE TITLE
declarative_base requires an "optional" argument

### ISSUE THREAD

**Issue by berislavlopac** [insightindustry/sqlathanor#30]
The first thing I ran into when replacing SQLAlchemy's `declarative_base` function with the one provided by SQLAthanor, I got this error:

    TypeError: declarative_base() missing 1 required positional argument: 'cls'

Checking the code, it turns out that it is indeed a positional argument, as the function [is defined](https://github.com/insightindustry/sqlathanor/blob/master/sqlathanor/declarative.py#L2646) thus:

    def declarative_base(cls, **kwargs):

While both the docstring and the actual code make it optional:

    def declarative_base(cls, **kwargs):
        """Construct a base class for declarative class definitions.

        [...]
        :param cls: Defaults to :class:`BaseModel` to provide  serialization/de-serialization
          support.
          If a :class:`tuple <python:tuple>` of classes, will include :class:`BaseModel`
          in that list of classes to mixin serialization/de-serialization support.
          If not :obj:`None <python:None>` and not a :class:`tuple <python:tuple>`, will mixin
          :class:`BaseModel` with the value passed to provide
          serialization/de-serialization support.
        :type cls: :obj:`None <python:None>` / :class:`tuple <python:tuple>` of classes / class object

        [...]
        """
        cls = kwargs.pop('cls', None)
        if cls is None:
            cls = BaseModel

I suggest fixing this issue in one of the following ways:

1. Remove the `cls` argument from the function definition. The rest of the code remains the same.
2. Redefine the function signature to include `cls=None` and remove the first line of the actual code.
3. Redefine the function signature to include cls=BaseModel and remove the first three lines of code (this is my favourite).

**Comment by insightindustry** [comment]
Thanks @berislavlopac ! Great catch! I like your proposed solution number 3 and will implement it later today.
