### ISSUE TITLE
Ignore/Repress Warnings?

### ISSUE THREAD

**Issue by bzaks1424** [insightindustry/sqlathanor#74]
Hey - Just curious - is it possible to repress the MaximumNestingExceededWarning output? There are times where I'd like to keep the nesting to 0 on purpose - but I don't want the warning in my logs.

Thanks again! I'm really happy with this!

**Comment by insightindustry** [comment]
Yep - it's possible to suppress the ``MaximumNestingExceededWarning`` using the Python standard library. Here's a [link to the Python docs](https://docs.python.org/3/library/warnings.html#the-warnings-filter).

Basically the way you would do this is something along the following lines:

    import sys
    from sqlathanor.errors import MaximumNestingExceededWarning

    if not sys.warnoptions:
        import warnings
        warnings.simplefilter('ignore::MaximumNestingExceededWarning')
    
and from that point forward the `MaximumNestingExceededWarning` should be filtered out / not displayed / not returned. Hope this helps!
