### ISSUE TITLE
new_from_dict doesn't seem to actually drop_extra_keys

### ISSUE THREAD

**Issue by bzaks1424** [insightindustry/sqlathanor#79]
When I'm creating a "task" object in my library:
I'm passing the following DICT:
```
{
'game_id': 'a6466202-f15c-408c-9959-8a18ec305a6c',
'task_definition_id': 'a441b376-4d87-45a8-8eac-5787acc6828f',
'sequence': 0,
'language_id': 'EN'
}
```

Then calling the following line of code:
```
newObj = PrimaryResource.new_from_dict(input_data=item, drop_extra_keys=True)
```

and getting the following exception:
```
Traceback (most recent call last):
  File "*/lib/python3.7/site-packages/chalice/app.py", line 1053, in _get_view_function_response
    response = view_function(**function_args)
  File "**/app.py", line 151, in getThings
    return _BasicRequest(app, tableName, Debug=debugMode)
  File "**/chalicelib/util.py", line 20, in _BasicRequest
    EncodeRelationshipLevel, Debug=Debug)
  File "**/chalicelib/util.py", line 98, in chalice_dispatch
    EncodeRelationshipLevel, Debug)
  File "***/Handler.py", line 100, in handle
    raise e
  File "***/Handler.py", line 96, in handle
    EncodeRelationshipLevel, Debug)
  File "***/Handler.py", line 145, in __genericHandler
    (status, response) = self.__do_db_call(QueryParams, Body, Debug)
  File "***/Handler.py", line 467, in __do_db_call
    self.__secondaryResource, QueryParams, Body, Debug))
  File "***/_Database.py", line 156, in _do_POST
    input_data=item, drop_extra_keys=True)
  File "**/vendor/sqlathanor/declarative/_dict_support.py", line 494, in new_from_dict
    config_set = config_set)
  File "**/vendor/sqlathanor/declarative/_dict_support.py", line 112, in _parse_dict
    raise ExtraKeyError("input data had extra keys: %s" % extra_keys)
sqlathanor.errors.ExtraKeyError: input data had extra keys: ['language_id']
```

**Comment by insightindustry** [comment]
Hmm. Okay, thanks - let me see if I can recreate this issue and diagnose what exactly is going on. While I suspect this won't have any bearing, just to be on the safe side, can you confirm which version of SQLAthanor you're running?

**Comment by insightindustry** [comment]
Ah - actually, one slight correction. See the [documentation](https://sqlathanor.readthedocs.io/en/latest/api.html#sqlathanor.declarative.BaseModel.new_from_dict).

The issue that arises here is that the default `error_on_extra_keys = True` is still being passed. Try adjusting your method call to the following:

    newObj = PrimaryResource.new_from_dict(input_data=item, error_on_extra_keys = False, drop_extra_keys=True)

and that should solve the issue. If it doesn't, then let me know and it will in fact be a bug.

**Comment by bzaks1424** [comment]
Ahhh! I had the logic backwards! Thank you!
Though a point of contention: what's the point of having drop extra keys as a parameter, and throwing an error that you have them? You'll literally never get past that point in the code without explicitly setting both variables.

Though that makes sense from a standpoint of - then you absolutely know.... 

I don't know - I just wanted to bring it up as a discussion.

**Comment by insightindustry** [comment]
Yeah, as a design question that's a perfectly good question. 

When it was originally implemented, there was some arcane edge-case reason for having the logic be that precise (or depending on point-of-view, that pedantic), but sitting here right now, I can't for the life of me recall what exactly the edge-case reasoning was. At this point, it's one of those items that making an API change to account for that is probably not worth the change to existing users who are using the library as-is already. 

One of those items that goes on the list of "refactor in a future upgrade, perhaps".

**Comment by bzaks1424** [comment]
Makes perfect sense! Thanks for the hyperspeed response as usual!
