### ISSUE TITLE
Issue with is_iterable validator when working with flask_sqlalchemy

### ISSUE THREAD

**Issue by aivrit** [insightindustry/sqlathanor#82]
Hi,
When using 0.5 together with flask_sqlalchemy, I encountered a problem when trying to use dump_to_dict on one of my defined models.
in the _to_dict function of _dict_support, when iterating on attributes, an attribute named query_class which holds the class "flask_sqlalchemy.BaseQuery" is iterated on.
Then, there's a check if it's iterable using checkers.is_iterable which uses the built-it python 
checker.
This checker only checks for an _iter__ function, which exists for the BaseQuery class even though it's not actually Iterable.
This fails the whole dump of course, raising a Type Error when trying to iterate over it.
 My suggestion is to add to the checkers.is_iterable function an assertion that also checks that the object is an instance of "Iterable".
I tested it locally and it fixes the issue.
Thanks!

**Comment by aivrit** [comment]
Realized now that this belongs to the validator_collection repository and not this one.

**Comment by aivrit** [comment]
opened https://github.com/insightindustry/validator-collection/issues/45 and https://github.com/insightindustry/validator-collection/pull/46 to fix this issue

**Comment by insightindustry** [comment]
Thanks - I've gone ahead and released a version of the Validator-Collection library (v.1.3.8) that fixes this issue. I'll update the dependency here in SQLAthanor in the next release.
