### ISSUE TITLE
Serialize a tuple of models (query returning 2+ model instances)?

### ISSUE THREAD

**Issue by Waddlen** [insightindustry/sqlathanor#86]
Hi, SQLAthanor is great. However, I'm confused if it's possible to serialize two or more related model instances at the same time. As an example, a class A that is one-to-many with class B and class C:

```python
Class A (BaseModel):
__tablename__ = 'a'
a_id = Column(db.Integer, primary_key=True, supports_dict=True, supports_json=True)
bs = relationship('b', backref='a', supports_dict=True, supports_json=True)
cs = relationship('c', backref='a', supports_dict=True, supports_json=True)
# <other fields>

Class B (BaseModel):
__tablename__ = 'b'
b_id = Column(db.Integer, primary_key=True, supports_dict=True, supports_json=True)
a_id = Column(db.ForeignKey('a.a_id'), nullable=False, supports_dict=True, supports_json=True)
# <other fields>

Class C (BaseModel):
__tablename__ = 'c'
a_id = Column(db.Integer, primary_key=True, supports_dict=True, supports_json=True)
a_id = Column(db.ForeignKey('a.a_id'), nullable=False, supports_dict=True, supports_json=True)
# <other fields>
```

I'm currently writing a query like `result = db.session.query(A,B).filter(*queries, A.a_id==B.a_id).first()`
which returns a tuple of `(<A object at 0x7f7bd5778910>, <B object at 0x7f7bd5778b10>)`

I can serialize either one of these individually, e.g. `result[0].to_dict(max_nesting=2)` for A, or `result[1].to_dict(max_nesting=2)` for B. My problem is that serializing A this way returns *all* instances of B rather than just the pairings from my query, and serializing B does not return A and all instances of C. The output of trying `result.to_dict(max_nesting=2)` is `AttributeError: 'result' object has no attribute 'to_dict'`

At the end of the day, I could serialize B and then run an additional query to re-grab the fields from A, as well as get all instances of C attached to A. But I'm wondering if there is a simpler and easier way to accomplish this. Thank you!

**Comment by insightindustry** [comment]
Sorry for the delay answering this question! It totally slipped through the cracks, and I didn't realize that it was still hanging around unanswered until prepping today's release.

I wish I had a better answer for you, but I'm afraid SQLAthanor can't help with applying a filter or a query on relationships nested within a model. Basically, as you mentioned, the way that SQLAthanor works is that it will try to serialize A, and by doing so it will serialize all of the Bs and Cs that are related to your A instance. There's currently no way to tell it "only serialize nested objects that meet criteria X, Y, and Z".

While I haven't given it a lot of thought, one possible pattern you may want to try is to handle the serialization of nested objects separately from the serialization of the parent object. So for example you may have something like the following:

   result = db.session.query(A, B).filter(*queries, A.a_id==B.a_id).first()
   parent = result[0]
   serialized_parent = result[0].to_dict(max_nesting = 0)
   child_bs = []
   for b_instance in parent.bs:
       if b_instance in result[1]:
          child_bs.append(b_instance.to_dict(max_nesting = 0))

The above is probably not going to be highly performant, but it should avoid forcing you to do multiple database roundtrips. However, you can likely optimize the code a little further using list comprehensions and identity / hashtable matching on instance attributes to squeeze some better performance out of it (also, I haven't tested it to validate whether the "instance in relationship" logic works correctly, but the principle should apply regardless of syntax).

Hope this helps, and sorry for the delay responding!
