### ISSUE TITLE
CannotCoerceError on 1:1 relationship between models (dict deserialization)

### ISSUE THREAD

**Issue by jonasmiederer** [insightindustry/sqlathanor#87]
Hi, thanks for your work on sqlathanor, I tried to get my hands on it today and thought it would come  in handy working with my SQLAlchemy models.

I tried to deserialize a dict-Object into my existing model, but it always fails. I'm working with a 1:1 relationship between to models.

Reducing this to a minimum working example, we can take the snippet from the _test_relationship_deserialize.py_ testcase.

If I take 
```python
def json_passes():
    return {
        'id': 1,
        'name': 'John Doe',
        'addresses': {
                'id': 2,
                'email': 'john@test.com',
                'user_id': 1
            }
    }
```

instead of 

```python
def json_passes():
    return {
        'id': 1,
        'name': 'John Doe',
        'addresses': []
    }
```

it raises a **CannotCoerceError**  from the validator_collection when calling `new_from_dict(input)`:
`validator_collection.errors.CannotCoerceError: value (id) cannot be coerced to a dict`

What am I doing wrong?
Thank you for your help!

**Comment by insightindustry** [comment]
Thanks, @JonasMie . The issue here is that the ``addresses`` property within the ``User`` model in that test case is a SQLAlchemy one-to-many relationship (one ``User`` to many ``Address`` records). Therefore, when you try to deserialize a single ``Address`` as a ``dict`` within your serialized ``User``, it is looking for an iterable of ``Address``-compatible ``dict`` objects.

If you want to model a 1:1 relationship, you'd need to model the ``relationship`` with ``uselist=False``. Here's the SQLAlchemy documentation for how to model a 1:1 relationship: https://docs.sqlalchemy.org/en/13/orm/basic_relationships.html#one-to-one

**Comment by JonasMie** [comment]
Thanks. @insightindustry for your reply!
I forgot that to mention in my post, I am actually using `uselist=False` on my model.
In the example it would be
```python
addresses = relationship("Address",
                             backref="user",
                             lazy="joined",
                             uselist=False,
                             supports_dict=True,
                             )
```
That is giving me the exact same error

**Comment by insightindustry** [comment]
Thanks, @JonasMie . 

In that case can you share with me the complete test case code that you are using to generate that exception? I _think_ I know what you're doing, but I'd like to make sure I'm mirroring your process correctly to reproduce and examine the bug.

**Comment by JonasMie** [comment]
Hi @insightindustry , sure! 
Here is the code:

```python
# -*- coding: utf-8 -*-

from sqlathanor import declarative_base, Column, relationship

from sqlalchemy import create_engine, Integer, String, Sequence, ForeignKey
from sqlalchemy.orm import sessionmaker

Base = declarative_base()


class User(Base):
    __tablename__ = 'users'

    id = Column(Integer,
                Sequence('user_id_seq'),
                primary_key=True,
                supports_dict=True,
                )

    name = Column(String,
                  supports_dict=True,
                  )

    address = relationship("Address",
                           backref="user",
                           lazy="joined",
                           uselist=False,
                           supports_dict=True,
                           )

    def __repr__(self):
        return "<User(id='{0:s}', name='{1:s}')>".format(
            str(self.id),
            self.name,
        )


class Address(Base):
    __tablename__ = 'addresses'

    id = Column(Integer,
                primary_key=True,
                supports_dict=True,
                )

    email = Column(String,
                   nullable=False,
                   supports_dict=True,
                   )

    user_id = Column(Integer,
                     ForeignKey('users.id'),
                     supports_dict=True,
                     )

    def __repr__(self):
        return "<Address(email='{0:s}')>".format(
            self.email,
        )


if __name__ == "__main__":
    engine = create_engine('sqlite:///')
    Base.metadata.create_all(engine)

    Session = sessionmaker(bind=engine)
    session = Session()

    input = {
        'id': 1,
        'name': 'John Doe',
        'address': {
            'id': 2,
            'email': 'john@test.com',
            'user_id': 1
        }
    }

    result = User.new_from_dict(input)
```

**Comment by TribuneX** [comment]
I have the same issue while trying to deserialize a one-to-one relationship from JSON. Any update on a possible solution to support one-to-one relationships?

**Comment by JonasMie** [comment]
Sorry not from my side, since I was just testing out whether this library will help me, so I didn't dig into it for too long and decided to go with my own deserializer
