### ISSUE TITLE
Support for lists of strings (and other primitive types)

### ISSUE THREAD

**Issue by TribuneX** [insightindustry/sqlathanor#90]
I want to deserialize the following JSON:

```json
{"domain-search": ["example.net", "example_two.net"]}
```

Is there a way to build an SQLathanor model which supports this JSON structure without custom `on_serialize` and `on_deserialize` methods?

I currently use this as a workaround:

```python
import sqlalchemy as sla
from sqlathanor import declarative_base, Column, relationship

Base = declarative_base()


class Example(Base):
    __tablename__ = "examples"

    def serialize_list(elements):
        return [element.value for element in elements]

    def deserialize_list(elements):
        return [ExampleDomainSearch(value=element) for element in elements]

    id = Column(sla.Integer, primary_key=True, nullable=False)

    domain_search = relationship("ExampleDomainSearch",
                                 supports_json=True,
                                 on_serialize=serialize_list,
                                 on_deserialize=deserialize_list)


class ExampleDomainSearch(Base):
    __tablename__ = "example_domain_searches"

    id = Column(sla.Integer, primary_key=True, nullable=False)

    value = Column(sla.String(255), nullable=False, supports_json=True)

    system_id = Column(sla.Integer, sla.ForeignKey("examples.id"))
```

**Comment by insightindustry** [comment]
@TribuneX Unfortunately, I can't think of a pattern that would get to your objective outside of using a custom `on_serialize` and `on_deserialize` function.

If it's a pattern that you use often across multiple models, one thing you could do that would save repeating code would be to build a base class (e.g. an abstracted base class, or a parent model that your actual models inherit from) with your `serialize_list` / `deserialize_list` methods. But in general, the workaround that you describe is probably the way to go to achieve your objective.
